M48
; DRILL file KiCad 10.0.1 date 2026-06-02T10:42:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-02T10:42:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X192.6Y-85.9
T2
X213.6Y-85.9
T3
X120.975Y-70.8
X121.175Y-90.4
X183.125Y-85.05
M30
